### ISSUE TITLE
Improvements to MyST Markdown

### ISSUE THREAD

**Issue by rowanc1** [econ-ark/REMARK#152]
The Econ-ARK team is working towards improvements to their tools, specifications and workflows to create reproducible, computational documents. This includes a focused effort to adopt MyST Markdown (https://mystmd.org) into the REMARK workflow. To do this, there are several identified improvements to be made in MyST, especially regarding:

- Table improvements (reading, rendering, export for LaTeX and Typst).
- Improved LaTeX support for existing projects (included subfiles, macros and common economics packages)
- Shared math macros, including via web-request
- Reproducibility checks and command line improvements to the REMARK tools.

The goal of this issue is to track these specific improvements that need to be made across that project and any documentation improvements in the REMARK repository.

## LaTeX improvements [14.5 days]

Tasks here will be turned into issues and pull requests as appropriate. This issue will be kept up to date as we refine and prioritize the work.

- [x] Math spacing for latex export https://github.com/executablebooks/mystmd/pull/1032 [0.5 days]
- [x] Parsing `longtable` and other tabular environments [2 days] executablebooks/mystmd#1041
- [x] Simple table alignment `| c |`
- [x] Better documentation of latex [0.5 days] --> myst https://github.com/executablebooks/mystmd/pull/1086
- [x] Recursive includes/inputs in latex [3 days] executablebooks/mystmd#1082
- [x] https://github.com/executablebooks/mystmd/issues/797
- [x] Page break: [1 day] https://github.com/executablebooks/mystmd/issues/714
- [x] Supporting macros/frontmatter across files [1.5 days] https://github.com/executablebooks/mystmd/pull/1156
- [x] Supporting math macros information [2 days] https://github.com/executablebooks/mystmd/pull/1218
- [x] Supporting extends [4 days] https://github.com/jupyter-book/mystmd/pull/1215, https://github.com/jupyter-book/mystmd/pull/1251
- [x] Supporting `stigma` ([example](https://mystmd.org/sandbox?tab=demo&myst=LQAtAC0ACgBtAGEAdABoADoACgAgACAAJwBcAHMAdABpAGcAbQBhACcAOgAgANsDCgAtAC0ALQAKAAoAJABBAHgAXgBcAHQAZQB4AHQAewBcAHMAdABpAGcAbQBhAH0AJAA%3D))
- [x] Sharing math macros, including via web-request executablebooks/mystmd#336

**Stretch Goals**

- [ ] math macros (multiple arguments)
- [ ] Support latex subfiles
- [ ] Table widths are preserved to and from latex
- [ ] Extensibility and plugins for latex parsing
- [ ] Table theme improvements (e.g. alignment (e.g. decimal alignment), borders)
- [ ] Math macros work in JupyterLab
- [ ] JupyterLab citations https://github.com/executablebooks/jupyterlab-myst/pull/161
- [ ] https://github.com/executablebooks/mystmd/issues/874
- [ ] https://github.com/executablebooks/mystmd/issues/711
- [ ] Better documentation of typst export

## Remark CLI [13.5 days]

The Python management CLI is now in the main branch.

For the econark CLI, we are extending MyST to:

- [x] Citation CFF creation [2 days] (single source of truth `myst build --cff`)
- [x] Readme Creation [2 days] (rendering markdown, markdown templating, export example)
- [x] Inherit standards [1 day] (allows for econ ark to create sharable config)
- [x] White labelling an econark CLI [4 days] (optional, can just use myst)
- [x] Citation CFF Test [4 days] (requires curvenote at the moment)
- [x] Report help [0.5 days]

## Examples [6 days]

- https://github.com/econ-ark/EpiExp
    - [x] extend to computational models [1day]
- https://github.com/llorracc/SolvingMicroDSOPs  [5days] (produces both paper and lecture notes)
   - [x] https://github.com/jupyter-book/mystmd/pull/1343
   - [x] https://github.com/jupyter-book/mystmd/pull/1342
   - [x] Finish up work and present progress [1 day]
   - [x] hyptertargets
   - [x] example of subfiles (use input!)
- https://github.com/econ-ark/BufferStockTheory (and latest)
   - [x] new theorem support
   - [ ] Conversion v1
   - [ ] Conversion v2 - https://github.com/llorracc/BufferStockTheory-Latest/issues/135

cc @alanlujan91 @llorracc
